New article: why you should be using new css features today - part 1
iodigital-com/io-technology pull request #131
Opened 2022-11-29 10:26 UTC by brechtDR

This is a new article on why you should be using new css features today. Ready for review.

This is part 1/2

2022-11-29 10:46 UTC, vanhoofmaarten commented on data/blog/why-you-should-be-using-new-css-features-today/why-you-should-be-using-new-css-features-today.md
> +Is it because they are cool, new and shiny? No, there is a lot more going on than that. Some of the latest things happening in CSS solve some of the biggest frustrations in web development. Just imag
Perhaps links to articles about these subjects already available on the TechHub?

Shameless plug: https://techhub.iodigital.com/articles/container-queries-the-next-step-towards-a-truly-modular-css

2022-11-29 10:46 UTC, vanhoofmaarten commented on data/blog/why-you-should-be-using-new-css-features-today/why-you-should-be-using-new-css-features-today.md
> +Is it because they are cool, new and shiny? No, there is a lot more going on than that. Some of the latest things happening in CSS solve some of the biggest frustrations in web development. Just imag
javascript -> JavaScript

2022-11-29 10:48 UTC, vanhoofmaarten commented on data/blog/why-you-should-be-using-new-css-features-today/why-you-should-be-using-new-css-features-today.md
> +But I hear you, you will be doing some more work while learning these new features. You will have to write some support flags in your CSS, you might need to set up some extra packages in your postCSS
postCSS -> PostCSS

2022-11-29 10:51 UTC, vanhoofmaarten commented on data/blog/why-you-should-be-using-new-css-features-today/why-you-should-be-using-new-css-features-today.md
> +If you are paying attention you might notice that my code just got larger and you’re right. Even the output of my code will be larger by a small margin. But I just received a newsflash from the clien
Add a comma after `attention`

2022-11-29 11:01 UTC, vanhoofmaarten requested changes
Thanks for this article @brechtDR, looking great! I spotted some inconsistencies with capitalization on brand names and some typos. Can you fix these?

2022-11-29 11:01 UTC, mrtnvh commented on data/blog/why-you-should-be-using-new-css-features-today/why-you-should-be-using-new-css-features-today.md
> +If you were using sass variables, you’d probably have to re-declare all your alerts scoped into media queries. But, because I used custom properties I can re-declare my custom properties:
sass -> Sass

2022-11-29 11:01 UTC, mrtnvh commented on data/blog/why-you-should-be-using-new-css-features-today/why-you-should-be-using-new-css-features-today.md
> +Also, CSS custom properties can be set by using JS, it makes playing around with css so much easier and doesn’t require you to set a whole bunch of inline styles on your dom. Just [take a look at thi
`makes playing around with css so much easier` -> `makes playing around with CSS so much easier`

2022-11-29 11:01 UTC, mrtnvh commented on data/blog/why-you-should-be-using-new-css-features-today/why-you-should-be-using-new-css-features-today.md
> +Also, CSS custom properties can be set by using JS, it makes playing around with css so much easier and doesn’t require you to set a whole bunch of inline styles on your dom. Just [take a look at thi
codepen -> CodePen

2022-11-29 11:01 UTC, mrtnvh commented on data/blog/why-you-should-be-using-new-css-features-today/why-you-should-be-using-new-css-features-today.md
> +A lot of people (including myself) have been using a 12 column Bootstrap flexbox grid for so long that it has become a second nature. Although design consistency is important when it comes to time ma
12 column -> 12-column
a second nature -> second nature

2022-11-29 11:01 UTC, mrtnvh commented on data/blog/why-you-should-be-using-new-css-features-today/why-you-should-be-using-new-css-features-today.md
> +You might wonder why we should make things harder than it used to be by declaring multiple grids on a website. \
than it used to be -> than they used to be

2022-11-29 11:01 UTC, mrtnvh commented on data/blog/why-you-should-be-using-new-css-features-today/why-you-should-be-using-new-css-features-today.md
> +With some careful CSS planning in your design system you can easily define your common patterns, so in the end, it’s only a small effort to create a front-end design system that’s a bit more unique a
nicely contained to the component -> nicely contained in the component

2022-11-29 11:01 UTC, mrtnvh commented on data/blog/why-you-should-be-using-new-css-features-today/why-you-should-be-using-new-css-features-today.md
> +There is still a lot missing at the moment before we can truly step away from SASS, especially when it comes to using variables in things such as media queries. But that doesn’t mean we can’t combine
SASS -> Sass

2022-11-29 11:01 UTC, mrtnvh commented on data/blog/why-you-should-be-using-new-css-features-today/why-you-should-be-using-new-css-features-today.md
> +I’m also a strong believer that clients will ask for more unique designs in the future, because at the moment there are a lot of webshops out there and a lot of them look more and less the same. Desi
Don't need a comma between `future` and `because`

2022-11-29 11:01 UTC, mrtnvh commented on data/blog/why-you-should-be-using-new-css-features-today/why-you-should-be-using-new-css-features-today.md
> +In no case, am I assaulting any use of frameworks, libraries and maybe tools that can purge your CSS from unneeded selectors. It’s about reflecting on how we can take our CSS game to the next level b
become a fully fledged CSS-developer -> becoming a fully-fledged CSS-developer

2022-11-29 11:13 UTC, brechtDR commented on data/blog/why-you-should-be-using-new-css-features-today/why-you-should-be-using-new-css-features-today.md
> +Is it because they are cool, new and shiny? No, there is a lot more going on than that. Some of the latest things happening in CSS solve some of the biggest frustrations in web development. Just imag
> https://techhub.iodigital.com/articles/container-queries-the-next-step-towards-a-truly-modular-css

I don't mind adding the link there. But i'm afraid that the article has become a bit outdated since it's still having container declarations without a specified name attached to it.

2022-11-29 11:21 UTC, brechtDR commented
Hey @vanhoofmaarten 

Thanks for the review.
I also added part 2 (was still checking this with Sander to see if that was possible "in draft")

I fixed most of the issues. The container queries blogpost seems to be a bit outdated at the moment. 
Maybe something you can look in to? I could add some links to it in part 2 then?

2022-11-29 12:30 UTC, DaveBitter commented
Nice! Could you maybe turn it into a series which makes it easier to navigate in the UI? You can refer to, for instance, this PR https://github.com/iodigital-com/io-technology/pull/111 to see how

2022-11-30 10:16 UTC, sanderdejong88 approved these changes

2022-11-30 10:17 UTC, merged