new article: Let's explore Astro's core features
iodigital-com/io-technology pull request #139
Opened 2022-12-05 15:15 UTC by playerfine

2022-12-05 18:30 UTC, vanhoofmaarten submitted a review, later dismissed

2022-12-05 18:30 UTC, vanhoofmaarten commented on data/blog/lets-explore-astros-core-features.md
> +Astro websites will typically load much faster than Next.js websites. This is due to the fact that Astro automatically removes unnecessary JavaScript from the page, hydrating only the individual comp
Can we rephrase this last sentence? Astro does not actually remove JS, it compiles the UI on the server to HTML. That's its actual power. Just output HTML, CSS and a sprinkle of JS where needed.

2022-12-05 18:30 UTC, vanhoofmaarten commented on data/blog/lets-explore-astros-core-features.md
> +Because NextJS does not yet support partial hydration, your website will be less performant because it will include a lot of unnecessary javascript.
javascript -> JavaScript

2022-12-05 18:30 UTC, vanhoofmaarten commented on data/blog/lets-explore-astros-core-features.md
> +Both NextJS and Astro are excellent website-building tools, however NextJS truly shines when it comes to applications, whereas Astro really shines when it comes to webpages with static content.
Nice addition, perhaps, the fact that the Astro team says they are content-focused themselves. https://docs.astro.build/en/concepts/why-astro/#content-focused

2022-12-05 18:30 UTC, vanhoofmaarten commented on data/blog/lets-explore-astros-core-features.md
> +The most important aspect of Astro components is that they render to HTML by default during the build process. Even if you run JavaScript code within your components, it will all be executed ahead of
javascript -> JavaScript

2022-12-05 18:30 UTC, vanhoofmaarten commented on data/blog/lets-explore-astros-core-features.md
> +Using the `<style/>` tag, you can begin writing styles in your astro component.
astro -> Astro

2022-12-05 18:30 UTC, vanhoofmaarten commented on data/blog/lets-explore-astros-core-features.md
> +endpoints can also return other HTTP methods functions for example `create`, `update`, `del` (delete).
Capital E?

2022-12-05 18:30 UTC, mrtnvh commented on data/blog/lets-explore-astros-core-features.md
> +If you believe Astro is deserving of its recent surge in popularity and want to give it a try, I would gladly refer you to their website and documentation at [https://astro.build/](https://astro.buil
Perhaps an `h2` titled `Conclusion` or something like that to wrap up this article?

2022-12-06 09:02 UTC, playerfine commented on data/blog/lets-explore-astros-core-features.md
> +Both NextJS and Astro are excellent website-building tools, however NextJS truly shines when it comes to applications, whereas Astro really shines when it comes to webpages with static content.
Yes, thats why I stated: "whereas Astro really shines when it comes to webpages with static content."

This should imply that they are focused on content based websites right?

2022-12-06 09:19 UTC, playerfine commented on data/blog/lets-explore-astros-core-features.md
> +Astro websites will typically load much faster than Next.js websites. This is due to the fact that Astro automatically removes unnecessary JavaScript from the page, hydrating only the individual comp
I think the last sentence is good as is it.
 
Astro renders the UI on the server and only sends the necessary JavaScript to the client, so in fact it actually removes/strips the Javascript, causing it to be a more performant websie

In their docs they stated: "In most cases, Astro websites will load significantly faster than Next.js websites. This is because Astro automatically strips unnecessary JavaScript from the page."

2022-12-06 10:36 UTC, ayoayco requested changes
Some suggestions! :)

2022-12-06 10:36 UTC, ayoayco commented on data/blog/lets-explore-astros-core-features.md
> +Astro islands are parts of the website that are built on the client side using JavaScript rather than delivered statically. This allows us to keep the majority of the site static while adding interac
> built on the client side using JavaScript rather than delivered statically

I think here it is more accurate to say that Island components are initially rendered server-side, but as the developer you can say you want it "hydrated" when it reaches the client. Performance benefit is: not all of component's JS needs to be in the client, only those needed for interaction.

2022-12-06 10:36 UTC, ayoayco commented on data/blog/lets-explore-astros-core-features.md
> +The architecture behind Astro Islands is called the Islands Architecture, whereby interactive UI components are hydrated with the [partial/progressive hydration technique](https://www.patterns.dev/po
I think this sentence about partial hydration needs to be in the previous paragraph after my last comment is clarified :)

2022-12-06 10:36 UTC, ayoayco commented on data/blog/lets-explore-astros-core-features.md
> +Due to the fact that each Astro Island is separately hydrated, you could develop them using any popular UI Framework, such as ReactJS:
Actually right now Framework components are the better way to develop Islands. Astro components are not designed to be hydrated: https://docs.astro.build/en/core-concepts/framework-components/#can-i-hydrate-astro-components

2022-12-06 10:36 UTC, ayoayco commented on data/blog/lets-explore-astros-core-features.md
> +
Can you add that there is currently an RFC to implement a new Client Directive for hydrating components "on interaction" https://github.com/withastro/rfcs/pull/278 😄 -- this will potentially similar performance improvements as other frameworks like Qwik is doing

2022-12-06 10:36 UTC, ayo-run commented on data/blog/lets-explore-astros-core-features.md
> +Astro is a comprehensive web framework that makes it simple to build content-rich, performance-oriented websites. Astro achieves this by delivering as minimal as possible JavaScript to the client; in
Maybe it's not a good idea to focus on MPA vs SPA... there was a successful exploration on implementing an SPA on an Astro page. :)

2022-12-06 10:36 UTC, ayoayco commented on data/blog/lets-explore-astros-core-features.md
> +
Let's also mention the RFC to have hybrid apps: Both SSR and SSG pages in a single app. :) This will bring the SPA vs MPA argument to rest, as we can now have SPAs in an Astro project: https://github.com/withastro/rfcs/pull/362

2022-12-06 10:39 UTC, ayoayco commented on data/blog/lets-explore-astros-core-features.md
> +Due to the fact that each Astro Island is separately hydrated, you could develop them using any popular UI Framework, such as ReactJS:
Astro components right now are viewed as the "ocean of static elements" :) and Islands of interactivity are the 3rd party components. Though technically you can ship JS to have interactivity in an Astro component

2022-12-06 10:53 UTC, ayoayco commented on data/blog/lets-explore-astros-core-features.md
> +Astro is a comprehensive web framework that makes it simple to build content-rich, performance-oriented websites. Astro achieves this by delivering as minimal as possible JavaScript to the client; in
I would say it is "MPA by default, but not impossible to implement an SPA within."

2022-12-06 10:58 UTC, ayoayco commented on data/blog/lets-explore-astros-core-features.md
> +Both NextJS and Astro are excellent website-building tools, however NextJS truly shines when it comes to applications, whereas Astro really shines when it comes to webpages with static content.
I think the link @vanhoofmaarten commented is good to mention here since we are comparing Next.js and Astro. Also a screenshot of this is nice so it is clear that even the team behind Astro acknowledges other frameworks

![Screenshot 2022-12-06 at 11 57 24 AM](https://user-images.githubusercontent.com/4262489/205893490-143f8d35-614a-431c-8f3a-4b049994d2a0.png)

2022-12-06 12:10 UTC, ayoayco commented on data/blog/lets-explore-astros-core-features.md
> +Both NextJS and Astro are excellent website-building tools, however NextJS truly shines when it comes to applications, whereas Astro really shines when it comes to webpages with static content.
Ah yeah, @playerfine now I also see your point in the sentence "whereas Astro really shines when it comes to webpages with static content." :) would just be cool to see Astro suggesting Next.js themselves too

2022-12-06 13:24 UTC, playerfine commented on data/blog/lets-explore-astros-core-features.md
> +
The RFC that you linked is for adding custom directives, not on interaction 

I think its better to only mention, features that are in Astro right now because we don't know how long its gonna take till its added to Astro. What do you think?

2022-12-06 13:50 UTC, ayoayco commented on data/blog/lets-explore-astros-core-features.md
> +
> I think its better to only mention features, that are in Astro right now
 Yup this is also good! 👍

2022-12-07 08:29 UTC, playerfine commented on data/blog/lets-explore-astros-core-features.md
> +
Same as before, I think its better to only focus on features that are currently in Astro

2022-12-07 08:39 UTC, ayo-run commented on data/blog/lets-explore-astros-core-features.md
> +
Yup, Cool!

2022-12-07 09:14 UTC, playerfine commented on data/blog/lets-explore-astros-core-features.md
> +Both NextJS and Astro are excellent website-building tools, however NextJS truly shines when it comes to applications, whereas Astro really shines when it comes to webpages with static content.
Yes,  I agree, thats why I stated:

> however NextJS truly shines when it comes to applications

2022-12-07 09:18 UTC, playerfine commented on data/blog/lets-explore-astros-core-features.md
> +Due to the fact that each Astro Island is separately hydrated, you could develop them using any popular UI Framework, such as ReactJS:
> Due to the fact that each Astro Island is separately hydrated, you could develop them using **any popular UI Framework**, such as ReactJS:

Implies that, Astro Islands are built with an UI Framework

2022-12-07 09:21 UTC, ayoayco commented on data/blog/lets-explore-astros-core-features.md
> +Due to the fact that each Astro Island is separately hydrated, you could develop them using any popular UI Framework, such as ReactJS:
I think on first reading it seemed to me that UI Frameworks are not the first option, when they should be. Maybe the wording "you _could_ develop them using"?

2022-12-07 10:05 UTC, playerfine commented on data/blog/lets-explore-astros-core-features.md
> +Astro is a comprehensive web framework that makes it simple to build content-rich, performance-oriented websites. Astro achieves this by delivering as minimal as possible JavaScript to the client; in
I dont really understand what you mean.

MPA's are websites that are rendered on a server on each page request from the client.
This is exactly what Astro does, this doesn't mean you cant have JavaScript components; These are just rendered on the server.

SPA do the contrary they render minimal html on the server, and hydrate the page will Javascript

2022-12-07 10:37 UTC, ayo-run commented
thanks @playerfine! 👍

2022-12-07 10:47 UTC, ayoayco commented on data/blog/lets-explore-astros-core-features.md
> +Astro is a comprehensive web framework that makes it simple to build content-rich, performance-oriented websites. Astro achieves this by delivering as minimal as possible JavaScript to the client; in
Yeah, I guess this is safest to keep how you wrote it. I just checked the current docs, and it's not yet obvious what the direction Astro is going, and mostly my information are coming from what's discussed in Discord channels.

2022-12-08 09:56 UTC, sanderdejong88 submitted a review, later dismissed

2022-12-12 11:56 UTC, sanderdejong88 approved these changes

2022-12-12 11:59 UTC, merged