Series: Frontend 💜 OpenAPI
iodigital-com/io-technology pull request #146
Opened 2022-12-23 13:49 UTC by vanhoofmaarten

Todo

- [ ] Refine article _Real live example of OpenAPI in a front-end project_: How to best refer to a project structure. Screenshots? Meh. IDK.
- [ ] Check SEO
- [ ] Review

2023-01-04 08:18 UTC, lucienimmink reviewed
Before go-live need to check the publication dates with @sanderdejong88

2023-01-04 08:19 UTC, lucienimmink requested changes
Publication dates need to be checked

2023-01-04 11:54 UTC, DaveBitter reviewed
Nice series!

2023-01-04 11:54 UTC, DaveBitter commented on data/blog/frontend-loves-openapi/let-us-introduce-you-to-openapi.md
> +title: 'Let us introduce you to OpenAPI'
Shouldn't this be 'Let me introduce you to OpenAPI"? Or is this an article together with somebody? In that case, you should add them to the authors array

2023-01-04 11:54 UTC, DaveBitter commented on data/blog/frontend-loves-openapi/let-us-introduce-you-to-openapi.md
> +Then, we'll define the data model with which our API provider will respond. This can be the entire definition of a component at once or a reference to a component defined in the root-level section Co
I noticed quite a few "then"'s. Perhaps nice to mix a few: "then", "next", "finally" etc.

Next to that, it looks like you're inconsistent with the comma when you start a sentence with "then"

2023-01-04 11:54 UTC, DaveBitter commented on data/blog/frontend-loves-openapi/let-your-restful-api-development-soar-with-open-api-tooling.md
> +We already mentioned putting an OpenAPI document in a Git repository to enable **versioning** of our API description. By utilising **Git submodules** and adding our OpenAPI document repository to our
Perhaps link to some of the tools you mention? For instace, Git Submodules

2023-01-24 07:48 UTC, vanhoofmaarten commented on data/blog/frontend-loves-openapi/let-us-introduce-you-to-openapi.md
> +title: 'Let us introduce you to OpenAPI'
Good point. It's just me rambling this time 😄

2023-01-24 14:15 UTC, vanhoofmaarten commented
> @lucienimmink  Publication dates need to be checked

@sanderdejong88 or @DaveBitter how are we going to publish this? I believe it doesn't make a lot of sense to release inclemently in the future, as I would be too excited to read everything at once. What do you say of a good old-skool Netflix release? Put the last article on todays date, and have each predecessor be a week earlier? This way it's a nice mix in the Articles list.

2023-02-03 11:33 UTC, vanhoofmaarten commented
@sanderdejong88 @DaveBitter Updated the publication dates.

2023-02-03 11:40 UTC, sanderdejong88 approved these changes

2023-02-03 11:44 UTC, merged